version: "3.5"
services:
  traefik:
    image: traefik:v1.7
    user: 0:1001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dockerdata/traefik/traefik.toml:/traefik.toml
    labels:
        - traefik.backend=traefik
        - traefik.frontend.rule=Host:traefik.homeland.ad
        - traefik.port=8080
        - traefik.docker.network=vmnet
    networks:
      - vmnet
    ports:
      - 80:80

  portainer:
    image: portainer/portainer
    user: 1001:999
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dockerdata/portainer:/data
    networks:
      - vmnet
    labels:
        - traefik.backend=portainer
        - traefik.frontend.rule=Host:portainer.homeland.ad
        - traefik.port=9000
        - traefik.docker.network=vmnet

  autoheal:
    image: willfarrell/autoheal:latest
    user: 1001:999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=120

networks:
  vmnet:
    external: true
